/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia.vista;

import java.text.ParseException;
import Farmacia.modelo.UsuarioMD;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.beans.binding.Bindings.select;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class Usuario extends javax.swing.JInternalFrame {
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    private DefaultTableModel modelo;
    public static ArrayList<UsuarioMD> listausuario = new ArrayList();
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
       
        modelo = new DefaultTableModel() {
            //CARGAR LOS CAMPOS
            public boolean iscelleditable(int fila, int columnas) {
                if (columnas == 7) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha_nacimiento");
        modelo.addColumn("Rol");
        modelo.addColumn("Nombre Usuario");
        modelo.addColumn("Clave");
        modelo.addColumn("Estado");
        
         //CREAR FILAS

        for (UsuarioMD listap : listausuario) {
            Object[] fila = new Object[7];
            fila[0] = listap.getCedula();
            fila[1] = listap.getNombres();
            fila[2] = listap.getFechaNacimiento();
            fila[3] = listap.getRol();
            fila[4] = listap.getNombreU();
            fila[5] = listap.getClave();
            fila[6] = listap.getEstado();
            modelo.addRow(fila);
        }
        
        tablaUsuario.setModel(modelo);
        nuevo();
        
    }

    public void limpiarTabla() {
        modelo.setRowCount(0); //LIMPIAR TABLA
        txtcedula1.setText("");
        txtnombre1.setText("");
        txtclave_u.setText("");
        txtnombre_u.setText("");      
        fecha_nacimiento.setDate(null);
    }

    public void actualizarTabla() {

        for (UsuarioMD listap : listausuario) {
            Object[] fila = new Object[7];
            fila[0] = listap.getCedula();
            fila[1] = listap.getNombres();
            fila[2] = listap.getFechaNacimiento();
            fila[3] = listap.getRol();
            fila[4] = listap.getNombreU();
            String c = listap.getClave();
            String a = "";
            for (int i = 0; i < c.length(); i++) {
                a = a + "*";
            }
            fila[5] = a;
            fila[6] = listap.getEstado();
            modelo.addRow(fila);
        }
        tablaUsuario.setModel(modelo);
    }

    public void nuevo() {
        btn_modificar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_guardar.setEnabled(false);
        txtcedula1.setEditable(false);
        txtnombre1.setEditable(false);
        fecha_nacimiento.setVisible(true);
        fecha_nacimiento.setEnabled(false);
        fecha_nacimiento.setDate(null);
        txtnombre_u.setEditable(false);
        txtclave_u.setEditable(false);       
        txtcedula1.setText("");
        txtnombre1.setText("");
        txtnombre_u.setText("");
        txtclave_u.setText("");
    }

    public void activarCampos() {
        txtcedula1.setText("");
        txtnombre1.setText("");
        txtclave_u.setText("");
        txtnombre_u.setText("");
        fecha_nacimiento.setDate(null);
        btn_guardar.setEnabled(true);
        txtcedula1.setEditable(true);
        txtnombre1.setEditable(true);
        fecha_nacimiento.setEnabled(true);
        txtnombre_u.setEditable(true);
        txtclave_u.setEditable(true);        
        combo_rol.setEnabled(true);
      
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcedula1 = new javax.swing.JTextField();
        txtnombre1 = new javax.swing.JTextField();
        txtnombre_u = new javax.swing.JTextField();
        txtclave_u = new javax.swing.JTextField();
        combo_rol = new javax.swing.JComboBox<>();
        fecha_nacimiento = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        btn_nuevo = new javax.swing.JButton();
        combo_estado = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("--Usuario--");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cedula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Fecha_nacimiento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Rol:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel5.setText("Nombre Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel6.setText("Clave:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));
        getContentPane().add(txtcedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));
        getContentPane().add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, -1));
        getContentPane().add(txtnombre_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 120, -1));
        getContentPane().add(txtclave_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 120, -1));

        combo_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Cliente", "Farmaceutico", "Proveedor" }));
        getContentPane().add(combo_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 130, -1));
        getContentPane().add(fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 30));

        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        btn_modificar.setText("MODIFICAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 600, 230));

        btn_nuevo.setText("NUEVO");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(combo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
         int a = JOptionPane.showConfirmDialog(null, "ESTA SEGURO QUE DESEA MODIFICAR", "CCONFIRMACION DE MODIFACION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            String fechan = formato.format(fecha_nacimiento.getDate());           
            int select = 0;
            listausuario.get(select).setNombres(txtnombre1.getText());       
            listausuario.get(select).setNombreU(txtnombre_u.getText());
            listausuario.get(select).setClave(txtclave_u.getText());
            listausuario.get(select).setFechaNacimiento(fechan);
            limpiarTabla();
            actualizarTabla();
            nuevo();
        } else {

        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        activarCampos();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
//        String fechan = formato.format(fechanacimiento.getDate());
//        //String rol =(String) comboRol.getSelectedItem();
//        if (txt_cedula.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "INGRESE LA CEDULA");
//        } else if (txt_cedula.getText().length() <= 9) {
//            JOptionPane.showMessageDialog(null, "CEDULA INCORRECTA");
//        } else if (txt_nombres.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "INGRESE EL NOMBRE");
//        } else if (fechanacimiento.getDate() == null) {
//            JOptionPane.showMessageDialog(null, "INGRESE LA FECHA DE NACIMIENTO");
//        } else if (Radio().equals("0")) {
//            JOptionPane.showMessageDialog(null, "SELECCIONE EL ESTADO");
//        } else if (comboRol.getSelectedItem().toString().equals("Seleccione")) {
//            JOptionPane.showMessageDialog(null, "SELECCIONE EL ROL");
//        } else if (txt_nombreUsuario.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "INGRESE EL NOMBRE DE USUARIO");
//        } else if (txt_clave.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "INGRESE LA CLAVE");
//        } else {
//            boolean a = false;
//            for (int i = 0; i < listausuario.size(); i++) {
//                if (listausuario.get(i).getCedula().equals(txt_cedula.getText())) {
//                    JOptionPane.showMessageDialog(null, "ESTA CEDULA YA EXISTE");
//                    txt_cedula.setText("");
//                    a = true;
//                    break;
//                }
//            }
//            if (a == false) {
//                int rol = (int) comboRol.getSelectedIndex();
//                Usuario usu = new Usuario(txt_cedula.getText(), txt_nombres.getText(), fechan, rol, txt_nombreUsuario.getText(), txt_clave.getText(), Radio());
//                listausuario.add(usu);
//                limpiarTabla();
//                actualizarTabla();
//                nuevo();
//            }
//        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
//         int select = tablaUsuario.getSelectedRow();
//        listausuario.get(select).setEstado("INACTIVO");
//        limpiarTabla();
//        actualizarTabla();
//        nuevo();
    }//GEN-LAST:event_btn_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JComboBox<String> combo_rol;
    private com.toedter.calendar.JCalendar fecha_nacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JTextField txtcedula1;
    private javax.swing.JTextField txtclave_u;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtnombre_u;
    // End of variables declaration//GEN-END:variables
}
