/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia.vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author A
 */
public class Vfarmaceutico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vfarmaceutico
     */
    public Vfarmaceutico() {
        initComponents();
    }

    public JButton getBtneliminarf() {
        return btneliminarf;
    }

    public void setBtneliminarf(JButton btneliminarf) {
        this.btneliminarf = btneliminarf;
    }

    public JButton getBtnguardarf() {
        return btnguardarf;
    }

    public void setBtnguardarf(JButton btnguardarf) {
        this.btnguardarf = btnguardarf;
    }

    public JButton getBtnmodificarf() {
        return btnmodificarf;
    }

    public void setBtnmodificarf(JButton btnmodificarf) {
        this.btnmodificarf = btnmodificarf;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JSpinner getjSpinner1() {
        return jSpinner1;
    }

    public void setjSpinner1(JSpinner jSpinner1) {
        this.jSpinner1 = jSpinner1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getTxtapellidofar() {
        return txtapellidofar;
    }

    public void setTxtapellidofar(JTextField txtapellidofar) {
        this.txtapellidofar = txtapellidofar;
    }

    public JTextField getTxtcodigofar() {
        return txtcodigofar;
    }

    public void setTxtcodigofar(JTextField txtcodigofar) {
        this.txtcodigofar = txtcodigofar;
    }

    public JTextField getTxtdireccionfar() {
        return txtdireccionfar;
    }

    public void setTxtdireccionfar(JTextField txtdireccionfar) {
        this.txtdireccionfar = txtdireccionfar;
    }

    public JTextField getTxtnombrefar() {
        return txtnombrefar;
    }

    public void setTxtnombrefar(JTextField txtnombrefar) {
        this.txtnombrefar = txtnombrefar;
    }

    public JTextField getTxttelefonofar() {
        return txttelefonofar;
    }

    public void setTxttelefonofar(JTextField txttelefonofar) {
        this.txttelefonofar = txttelefonofar;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigofar = new javax.swing.JTextField();
        txtnombrefar = new javax.swing.JTextField();
        txtapellidofar = new javax.swing.JTextField();
        txttelefonofar = new javax.swing.JTextField();
        txtdireccionfar = new javax.swing.JTextField();
        btnguardarf = new javax.swing.JButton();
        btnmodificarf = new javax.swing.JButton();
        btneliminarf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("--FARMACEUTICO--");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));
        getContentPane().add(txtcodigofar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, -1));
        getContentPane().add(txtnombrefar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));
        getContentPane().add(txtapellidofar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, -1));
        getContentPane().add(txttelefonofar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 150, -1));
        getContentPane().add(txtdireccionfar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 150, -1));

        btnguardarf.setText("GUARDAR");
        getContentPane().add(btnguardarf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        btnmodificarf.setText("MODIFICAR");
        getContentPane().add(btnmodificarf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        btneliminarf.setText("ELIMINAR");
        getContentPane().add(btneliminarf, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 570, 260));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Farmacia_imagenes/bf23243e1726ccaba8c70279e963e849-grafico-vectorial-de-fondo-azul-abstracto.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminarf;
    private javax.swing.JButton btnguardarf;
    private javax.swing.JButton btnmodificarf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtapellidofar;
    private javax.swing.JTextField txtcodigofar;
    private javax.swing.JTextField txtdireccionfar;
    private javax.swing.JTextField txtnombrefar;
    private javax.swing.JTextField txttelefonofar;
    // End of variables declaration//GEN-END:variables
}
