/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia.vista;

import java.awt.Dimension;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;

/**
 *
 * @author A
 */
public class Vmenu extends javax.swing.JFrame {

    /**
     * Creates new form Vmenu
     */
    public Vmenu() {
        initComponents();
    }

    public JCheckBoxMenuItem getBtn_persona() {
        return Btn_persona;
    }

    public void setBtn_persona(JCheckBoxMenuItem Btn_persona) {
        this.Btn_persona = Btn_persona;
    }

    public JCheckBoxMenuItem getBtn_rol() {
        return Btn_rol;
    }

    public void setBtn_rol(JCheckBoxMenuItem Btn_rol) {
        this.Btn_rol = Btn_rol;
    }

    public JCheckBoxMenuItem getBtn_usuario() {
        return Btn_usuario;
    }

    public void setBtn_usuario(JCheckBoxMenuItem Btn_usuario) {
        this.Btn_usuario = Btn_usuario;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Btn_persona = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Btn_usuario = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Btn_rol = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jMenu1.setText("Persona");

        Btn_persona.setSelected(true);
        Btn_persona.setText("Person");
        Btn_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_personaActionPerformed(evt);
            }
        });
        jMenu1.add(Btn_persona);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario");

        Btn_usuario.setSelected(true);
        Btn_usuario.setText("User");
        Btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_usuarioActionPerformed(evt);
            }
        });
        jMenu2.add(Btn_usuario);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Rol");

        Btn_rol.setSelected(true);
        Btn_rol.setText("Rol");
        Btn_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_rolActionPerformed(evt);
            }
        });
        jMenu3.add(Btn_rol);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_personaActionPerformed
       Vpersona es = new Vpersona();
       jDesktopPane1.add(es);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = es.getSize();
       es.setLocation((desktopSize.width - FrameSize.width)/2,
               (desktopSize.height- FrameSize.height)/2);
       es.show();
       es.setVisible(true);
    }//GEN-LAST:event_Btn_personaActionPerformed

    private void Btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_usuarioActionPerformed
       Vusuario es = new Vusuario();
       jDesktopPane1.add(es);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = es.getSize();
       es.setLocation((desktopSize.width - FrameSize.width)/2,
               (desktopSize.height- FrameSize.height)/2);
       es.show();
       es.setVisible(true);
    }//GEN-LAST:event_Btn_usuarioActionPerformed

    private void Btn_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_rolActionPerformed
       Vrol es = new Vrol();
       jDesktopPane1.add(es);
       Dimension desktopSize = jDesktopPane1.getSize();
       Dimension FrameSize = es.getSize();
       es.setLocation((desktopSize.width - FrameSize.width)/2,
               (desktopSize.height- FrameSize.height)/2);
       es.show();
       es.setVisible(true);
    }//GEN-LAST:event_Btn_rolActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Vmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Vmenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Btn_persona;
    private javax.swing.JCheckBoxMenuItem Btn_rol;
    private javax.swing.JCheckBoxMenuItem Btn_usuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
