/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ISTA kelly A
 */
public class vcliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form vcliente
     */
    public vcliente() {
        initComponents();
    }

    public JButton getBtnbuscar() {
        return Btnbuscar;
    }

    public void setBtnbuscar(JButton Btnbuscar) {
        this.Btnbuscar = Btnbuscar;
    }

    public JButton getBtneliminar() {
        return Btneliminar;
    }

    public void setBtneliminar(JButton Btneliminar) {
        this.Btneliminar = Btneliminar;
    }

    public JButton getBtnguardar() {
        return Btnguardar;
    }

    public void setBtnguardar(JButton Btnguardar) {
        this.Btnguardar = Btnguardar;
    }

    public JButton getBtnimprimirc() {
        return Btnimprimirc;
    }

    public void setBtnimprimirc(JButton Btnimprimirc) {
        this.Btnimprimirc = Btnimprimirc;
    }

    public JButton getBtnmodificar() {
        return Btnmodificar;
    }

    public void setBtnmodificar(JButton Btnmodificar) {
        this.Btnmodificar = Btnmodificar;
    }

    public JButton getBtnnuevo() {
        return Btnnuevo;
    }

    public void setBtnnuevo(JButton Btnnuevo) {
        this.Btnnuevo = Btnnuevo;
    }

    public JLabel getFot() {
        return fot;
    }

    public void setFot(JLabel fot) {
        this.fot = fot;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTabla_cliente() {
        return tabla_cliente;
    }

    public void setTabla_cliente(JTable tabla_cliente) {
        this.tabla_cliente = tabla_cliente;
    }

    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }

    public JTextField getTxtcedula() {
        return txtcedula;
    }

    public void setTxtcedula(JTextField txtcedula) {
        this.txtcedula = txtcedula;
    }

    public JTextField getTxtdescrip() {
        return txtdescrip;
    }

    public void setTxtdescrip(JTextField txtdescrip) {
        this.txtdescrip = txtdescrip;
    }

    public JTextField getTxtnomyap() {
        return txtnomyap;
    }

    public void setTxtnomyap(JTextField txtnomyap) {
        this.txtnomyap = txtnomyap;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnomyap = new javax.swing.JTextField();
        txtdescrip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fot = new javax.swing.JLabel();
        Btnnuevo = new javax.swing.JButton();
        Btnguardar = new javax.swing.JButton();
        Btnmodificar = new javax.swing.JButton();
        Btneliminar = new javax.swing.JButton();
        Btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        Btnimprimirc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("**CLIENTE**");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("**Registro de Cliente**");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Nombres y Apellidos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("Descripcion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, -1));
        getContentPane().add(txtnomyap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));
        getContentPane().add(txtdescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));

        jLabel5.setText("Foto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        fot.setText("foto");
        getContentPane().add(fot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 90));

        Btnnuevo.setText("Nuevo");
        getContentPane().add(Btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        Btnguardar.setText("Guardar");
        getContentPane().add(Btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        Btnmodificar.setText("Modificar");
        getContentPane().add(Btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        Btneliminar.setText("Eliminar");
        getContentPane().add(Btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        Btnbuscar.setText("Buscar");
        getContentPane().add(Btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 170, -1));

        Btnimprimirc.setText("Imprimir");
        getContentPane().add(Btnimprimirc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, -1));

        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres y Apellidos", "Descripcion", "Foto"
            }
        ));
        jScrollPane1.setViewportView(tabla_cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 570, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbuscar;
    private javax.swing.JButton Btneliminar;
    private javax.swing.JButton Btnguardar;
    private javax.swing.JButton Btnimprimirc;
    private javax.swing.JButton Btnmodificar;
    private javax.swing.JButton Btnnuevo;
    private javax.swing.JLabel fot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_cliente;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdescrip;
    private javax.swing.JTextField txtnomyap;
    // End of variables declaration//GEN-END:variables
}
