/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author VICO5
 */
public class vprincipal extends javax.swing.JFrame {

    /**
     * Creates new form vprincipal
     */
    public vprincipal() {
        initComponents();
    }

    public JMenuItem getBtn_productos() {
        return btn_productos;
    }

    public void setBtn_productos(JMenuItem btn_productos) {
        this.btn_productos = btn_productos;
    }

    public JMenu getMenuproductos() {
        return menuproductos;
    }

    public void setMenuproductos(JMenu menuproductos) {
        this.menuproductos = menuproductos;
    }

    public JMenuItem getBtn_cliente() {
        return btn_cliente;
    }

    public void setBtn_cliente(JMenuItem btn_cliente) {
        this.btn_cliente = btn_cliente;
    }

    public JMenuItem getBtn_persona() {
        return btn_persona;
    }

    public void setBtn_persona(JMenuItem btn_persona) {
        this.btn_persona = btn_persona;
    }

    public JMenuItem getBtn_rol() {
        return btn_rol;
    }

    public void setBtn_rol(JMenuItem btn_rol) {
        this.btn_rol = btn_rol;
    }

    public JMenuItem getBtn_salir() {
        return btn_salir;
    }

    public void setBtn_salir(JMenuItem btn_salir) {
        this.btn_salir = btn_salir;
    }

    public JMenuItem getBtn_usuario() {
        return btn_usuario;
    }

    public void setBtn_usuario(JMenuItem btn_usuario) {
        this.btn_usuario = btn_usuario;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenu getMenucliente() {
        return menucliente;
    }

    public void setMenucliente(JMenu menucliente) {
        this.menucliente = menucliente;
    }

    public JMenu getMenupersona() {
        return menupersona;
    }

    public void setMenupersona(JMenu menupersona) {
        this.menupersona = menupersona;
    }

    public JMenu getMenurol() {
        return menurol;
    }

    public void setMenurol(JMenu menurol) {
        this.menurol = menurol;
    }

    public JMenu getMenusalir() {
        return menusalir;
    }

    public void setMenusalir(JMenu menusalir) {
        this.menusalir = menusalir;
    }

    public JMenu getMenuusuario() {
        return menuusuario;
    }

    public void setMenuusuario(JMenu menuusuario) {
        this.menuusuario = menuusuario;
    }

    public JMenuItem getBtn_proveedor() {
        return btn_proveedor;
    }

    public void setBtn_proveedor(JMenuItem btn_proveedor) {
        this.btn_proveedor = btn_proveedor;
    }

    public JMenu getMenupro() {
        return menupro;
    }

    public void setMenupro(JMenu menupro) {
        this.menupro = menupro;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menupersona = new javax.swing.JMenu();
        btn_persona = new javax.swing.JMenuItem();
        menurol = new javax.swing.JMenu();
        btn_rol = new javax.swing.JMenuItem();
        menuusuario = new javax.swing.JMenu();
        btn_usuario = new javax.swing.JMenuItem();
        menucliente = new javax.swing.JMenu();
        btn_cliente = new javax.swing.JMenuItem();
        menupro = new javax.swing.JMenu();
        btn_proveedor = new javax.swing.JMenuItem();
        menuproductos = new javax.swing.JMenu();
        btn_productos = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenu();
        btn_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        menupersona.setText("Persona");

        btn_persona.setText("Persona");
        menupersona.add(btn_persona);

        jMenuBar1.add(menupersona);

        menurol.setText("Rol");

        btn_rol.setText("Rol");
        menurol.add(btn_rol);

        jMenuBar1.add(menurol);

        menuusuario.setText("Usuario");

        btn_usuario.setText("Usuario");
        menuusuario.add(btn_usuario);

        jMenuBar1.add(menuusuario);

        menucliente.setText("Cliente");

        btn_cliente.setText("Cliente");
        menucliente.add(btn_cliente);

        jMenuBar1.add(menucliente);

        menupro.setText("Proveedor");

        btn_proveedor.setText("Proveedor");
        menupro.add(btn_proveedor);

        jMenuBar1.add(menupro);

        menuproductos.setText("Productos");

        btn_productos.setText("Porductos");
        menuproductos.add(btn_productos);

        jMenuBar1.add(menuproductos);

        menusalir.setText("Salir");

        btn_salir.setText("Salir");
        menusalir.add(btn_salir);

        jMenuBar1.add(menusalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_cliente;
    private javax.swing.JMenuItem btn_persona;
    private javax.swing.JMenuItem btn_productos;
    private javax.swing.JMenuItem btn_proveedor;
    private javax.swing.JMenuItem btn_rol;
    private javax.swing.JMenuItem btn_salir;
    private javax.swing.JMenuItem btn_usuario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menucliente;
    private javax.swing.JMenu menupersona;
    private javax.swing.JMenu menupro;
    private javax.swing.JMenu menuproductos;
    private javax.swing.JMenu menurol;
    private javax.swing.JMenu menusalir;
    private javax.swing.JMenu menuusuario;
    // End of variables declaration//GEN-END:variables
}
