/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JCheckBoxMenuItem;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author VICO5
 */
public class vprincipal extends javax.swing.JFrame {

    /**
     * Creates new form vprincipal
     */
    public vprincipal() {
        initComponents();
    }

    public JMenuItem getBtn_persona() {
        return btn_persona;
    }

    public void setBtn_persona(JMenuItem btn_persona) {
        this.btn_persona = btn_persona;
    }

    public JMenuItem getBtn_rol() {
        return btn_rol;
    }

    public void setBtn_rol(JMenuItem btn_rol) {
        this.btn_rol = btn_rol;
    }

    public JMenuItem getBtn_salir() {
        return btn_salir;
    }

    public void setBtn_salir(JMenuItem btn_salir) {
        this.btn_salir = btn_salir;
    }

    public JMenuItem getBtn_usuario() {
        return btn_usuario;
    }

    public void setBtn_usuario(JMenuItem btn_usuario) {
        this.btn_usuario = btn_usuario;
    }

    public JCheckBoxMenuItem getBtncliente() {
        return btncliente;
    }

    public void setBtncliente(JCheckBoxMenuItem btncliente) {
        this.btncliente = btncliente;
    }

    public JMenu getBtnproductos() {
        return btnproductos;
    }

    public void setBtnproductos(JMenu btnproductos) {
        this.btnproductos = btnproductos;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JCheckBoxMenuItem getjCheckBoxMenuItem1() {
        return jCheckBoxMenuItem1;
    }

    public void setjCheckBoxMenuItem1(JCheckBoxMenuItem jCheckBoxMenuItem1) {
        this.jCheckBoxMenuItem1 = jCheckBoxMenuItem1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenu getjMenu5() {
        return jMenu5;
    }

    public void setjMenu5(JMenu jMenu5) {
        this.jMenu5 = jMenu5;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_persona = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btn_usuario = new javax.swing.JMenuItem();
        btnproductos = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btn_rol = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btncliente = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btn_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jMenu1.setText("Persona");

        btn_persona.setText("Persona");
        jMenu1.add(btn_persona);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario");

        btn_usuario.setText("Usuario");
        jMenu2.add(btn_usuario);

        jMenuBar1.add(jMenu2);

        btnproductos.setText("Productos");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("productos");
        btnproductos.add(jCheckBoxMenuItem1);

        jMenuBar1.add(btnproductos);

        jMenu3.setText("Rol");

        btn_rol.setText("Rol");
        jMenu3.add(btn_rol);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Cliente");

        btncliente.setSelected(true);
        btncliente.setText("cliente");
        jMenu5.add(btncliente);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Salir");

        btn_salir.setText("Salir");
        jMenu4.add(btn_salir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vprincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_persona;
    private javax.swing.JMenuItem btn_rol;
    private javax.swing.JMenuItem btn_salir;
    private javax.swing.JMenuItem btn_usuario;
    private javax.swing.JCheckBoxMenuItem btncliente;
    private javax.swing.JMenu btnproductos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
