/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ISTA kelly a
 */
public class vproductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form vproductos
     */
    public vproductos() {
        initComponents();
    }

    public JButton getBtnbuscar01() {
        return Btnbuscar01;
    }

    public void setBtnbuscar01(JButton Btnbuscar01) {
        this.Btnbuscar01 = Btnbuscar01;
    }

    public JButton getBtneliminar01() {
        return Btneliminar01;
    }

    public void setBtneliminar01(JButton Btneliminar01) {
        this.Btneliminar01 = Btneliminar01;
    }

    public JButton getBtnfoto() {
        return Btnfoto;
    }

    public void setBtnfoto(JButton Btnfoto) {
        this.Btnfoto = Btnfoto;
    }

    public JButton getBtnguardar01() {
        return Btnguardar01;
    }

    public void setBtnguardar01(JButton Btnguardar01) {
        this.Btnguardar01 = Btnguardar01;
    }

    public JButton getBtnimprimirp() {
        return Btnimprimirp;
    }

    public void setBtnimprimirp(JButton Btnimprimirp) {
        this.Btnimprimirp = Btnimprimirp;
    }

    public JButton getBtnmodificar01() {
        return Btnmodificar01;
    }

    public void setBtnmodificar01(JButton Btnmodificar01) {
        this.Btnmodificar01 = Btnmodificar01;
    }

    public JButton getBtnnuevo01() {
        return Btnnuevo01;
    }

    public void setBtnnuevo01(JButton Btnnuevo01) {
        this.Btnnuevo01 = Btnnuevo01;
    }

    public JLabel getFoto() {
        return foto;
    }

    public void setFoto(JLabel foto) {
        this.foto = foto;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTablaproductos() {
        return tablaproductos;
    }

    public void setTablaproductos(JTable tablaproductos) {
        this.tablaproductos = tablaproductos;
    }

    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }

    public JTextField getTxtdescripcion() {
        return txtdescripcion;
    }

    public void setTxtdescripcion(JTextField txtdescripcion) {
        this.txtdescripcion = txtdescripcion;
    }

    public JTextField getTxtid() {
        return txtid;
    }

    public void setTxtid(JTextField txtid) {
        this.txtid = txtid;
    }

    public JTextField getTxtnomproductos() {
        return txtnomproductos;
    }

    public void setTxtnomproductos(JTextField txtnomproductos) {
        this.txtnomproductos = txtnomproductos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtnomproductos = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        Btnnuevo01 = new javax.swing.JButton();
        Btnguardar01 = new javax.swing.JButton();
        Btnmodificar01 = new javax.swing.JButton();
        Btneliminar01 = new javax.swing.JButton();
        Btnbuscar01 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproductos = new javax.swing.JTable();
        Btnimprimirp = new javax.swing.JButton();
        Btnfoto = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("**PRODUCTOS**");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Registro de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Productos ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText(" Nombres de Productos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Descripcion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setText("Foto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        foto.setText("foto");
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 110));
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 30, 160, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, -1));
        getContentPane().add(txtnomproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, -1));
        getContentPane().add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, -1));

        Btnnuevo01.setText("Nuevo");
        getContentPane().add(Btnnuevo01, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        Btnguardar01.setText("Guardar");
        getContentPane().add(Btnguardar01, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        Btnmodificar01.setText("Modificar");
        getContentPane().add(Btnmodificar01, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        Btneliminar01.setText("Eliminar");
        getContentPane().add(Btneliminar01, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        Btnbuscar01.setText("Buscar");
        getContentPane().add(Btnbuscar01, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        tablaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Productos", "Nombre Productos", "Descripcion", "Foto"
            }
        ));
        jScrollPane1.setViewportView(tablaproductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 580, 300));

        Btnimprimirp.setText("Imprimir");
        getContentPane().add(Btnimprimirp, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        Btnfoto.setText("foto");
        getContentPane().add(Btnfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbuscar01;
    private javax.swing.JButton Btneliminar01;
    private javax.swing.JButton Btnfoto;
    private javax.swing.JButton Btnguardar01;
    private javax.swing.JButton Btnimprimirp;
    private javax.swing.JButton Btnmodificar01;
    private javax.swing.JButton Btnnuevo01;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproductos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnomproductos;
    // End of variables declaration//GEN-END:variables
}
