/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ISTA kelly a
 */
public class vproveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form vproveedores
     */
    public vproveedores() {
        initComponents();
    }

    public JButton getBtnbuscar02() {
        return Btnbuscar02;
    }

    public void setBtnbuscar02(JButton Btnbuscar02) {
        this.Btnbuscar02 = Btnbuscar02;
    }

    public JButton getBtneliminar() {
        return Btneliminar;
    }

    public void setBtneliminar(JButton Btneliminar) {
        this.Btneliminar = Btneliminar;
    }

    public JButton getBtnguardar02() {
        return Btnguardar02;
    }

    public void setBtnguardar02(JButton Btnguardar02) {
        this.Btnguardar02 = Btnguardar02;
    }

    public JButton getBtnimprimirp02() {
        return Btnimprimirp02;
    }

    public void setBtnimprimirp02(JButton Btnimprimirp02) {
        this.Btnimprimirp02 = Btnimprimirp02;
    }

    public JButton getBtnmodificar02() {
        return Btnmodificar02;
    }

    public void setBtnmodificar02(JButton Btnmodificar02) {
        this.Btnmodificar02 = Btnmodificar02;
    }

    public JButton getBtnnuevo02() {
        return Btnnuevo02;
    }

    public void setBtnnuevo02(JButton Btnnuevo02) {
        this.Btnnuevo02 = Btnnuevo02;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTablaproveedor() {
        return tablaproveedor;
    }

    public void setTablaproveedor(JTable tablaproveedor) {
        this.tablaproveedor = tablaproveedor;
    }

    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }

    public JTextField getTxtceltelf() {
        return txtceltelf;
    }

    public void setTxtceltelf(JTextField txtceltelf) {
        this.txtceltelf = txtceltelf;
    }

    public JTextField getTxtcod() {
        return txtcod;
    }

    public void setTxtcod(JTextField txtcod) {
        this.txtcod = txtcod;
    }

    public JTextField getTxtcorreo() {
        return txtcorreo;
    }

    public void setTxtcorreo(JTextField txtcorreo) {
        this.txtcorreo = txtcorreo;
    }

    public JTextField getTxtdirec() {
        return txtdirec;
    }

    public void setTxtdirec(JTextField txtdirec) {
        this.txtdirec = txtdirec;
    }

    public JTextField getTxtnomcompletos() {
        return txtnomcompletos;
    }

    public void setTxtnomcompletos(JTextField txtnomcompletos) {
        this.txtnomcompletos = txtnomcompletos;
    }

    public JTextField getTxtpedido() {
        return txtpedido;
    }

    public void setTxtpedido(JTextField txtpedido) {
        this.txtpedido = txtpedido;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpedido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        txtceltelf = new javax.swing.JTextField();
        txtnomcompletos = new javax.swing.JTextField();
        txtcod = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        Btnnuevo02 = new javax.swing.JButton();
        Btnguardar02 = new javax.swing.JButton();
        Btnmodificar02 = new javax.swing.JButton();
        Btneliminar = new javax.swing.JButton();
        Btnbuscar02 = new javax.swing.JButton();
        Btnimprimirp02 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproveedor = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("**Proveedores**");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Registro de Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Nombres Completos:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("Celular o Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel7.setText("Pedido:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        getContentPane().add(txtpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, -1));
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        txtdirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirecActionPerformed(evt);
            }
        });
        getContentPane().add(txtdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, -1));
        getContentPane().add(txtceltelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));
        getContentPane().add(txtnomcompletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, -1));
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 220, -1));

        Btnnuevo02.setText("Nuevo");
        getContentPane().add(Btnnuevo02, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        Btnguardar02.setText("Guardar");
        getContentPane().add(Btnguardar02, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        Btnmodificar02.setText("Modificar");
        getContentPane().add(Btnmodificar02, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        Btneliminar.setText("Eliminar");
        getContentPane().add(Btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        Btnbuscar02.setText("Buscar");
        Btnbuscar02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnbuscar02ActionPerformed(evt);
            }
        });
        getContentPane().add(Btnbuscar02, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        Btnimprimirp02.setText("Imprimir");
        getContentPane().add(Btnimprimirp02, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, -1, -1));

        tablaproveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombres Completos", "Celular o Telefono", "Direccion", "Correo", "Pedido"
            }
        ));
        jScrollPane1.setViewportView(tablaproveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 670, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdirecActionPerformed

    private void Btnbuscar02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnbuscar02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btnbuscar02ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnbuscar02;
    private javax.swing.JButton Btneliminar;
    private javax.swing.JButton Btnguardar02;
    private javax.swing.JButton Btnimprimirp02;
    private javax.swing.JButton Btnmodificar02;
    private javax.swing.JButton Btnnuevo02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproveedor;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtceltelf;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtnomcompletos;
    private javax.swing.JTextField txtpedido;
    // End of variables declaration//GEN-END:variables
}
