/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Papeleria_Bella.vista;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author hp
 */
public class Vprincipal extends javax.swing.JFrame {
 public Vprincipal() {
        initComponents();
    }

    public JLabel getLabelNombres() {
        return labelNombres;
    }

    public void setLabelNombres(JLabel labelNombres) {
        this.labelNombres = labelNombres;
    }

    public JMenuItem getItemclientes() {
        return itemclientes;
    }

    public void setItemclientes(JMenuItem itemclientes) {
        this.itemclientes = itemclientes;
    }

    public JMenuItem getItemcotizacion() {
        return itemcotizacion;
    }

    public void setItemcotizacion(JMenuItem itemcotizacion) {
        this.itemcotizacion = itemcotizacion;
    }

    public JMenu getItemotros() {
        return itemotros;
    }

    public void setItemotros(JMenu itemotros) {
        this.itemotros = itemotros;
    }

    public JMenuItem getItemreportes() {
        return itemreportes;
    }

    public void setItemreportes(JMenuItem itemreportes) {
        this.itemreportes = itemreportes;
    }

    public JMenuItem getItemstock() {
        return itemstock;
    }

    public void setItemstock(JMenuItem itemstock) {
        this.itemstock = itemstock;
    }

    public JMenuItem getItemventas() {
        return itemventas;
    }

    public void setItemventas(JMenuItem itemventas) {
        this.itemventas = itemventas;
    }
 

    public JMenuItem getItemroles() {
        return itemroles;
    }

    public void setItemroles(JMenuItem itemroles) {
        this.itemroles = itemroles;
    }

    public JMenuItem getItemempresa() {
        return itemempresa;
    }

    public void setItemempresa(JMenuItem itemempresa) {
        this.itemempresa = itemempresa;
    }

    public JMenu getIteminformacion() {
        return iteminformacion;
    }

    public void setIteminformacion(JMenu iteminformacion) {
        this.iteminformacion = iteminformacion;
    }

    public JMenuItem getItemproveedores() {
        return itemproveedores;
    }

    public void setItemproveedores(JMenuItem itemproveedores) {
        this.itemproveedores = itemproveedores;
    }

    
    
 

    public JMenuItem getItempersona() {
        return itempersona;
    }

    public void setItempersona(JMenuItem itempersona) {
        this.itempersona = itempersona;
    }

    public JMenuItem getItemusuario() {
        return itemusuario;
    }

    public void setItemusuario(JMenuItem itemusuario) {
        this.itemusuario = itemusuario;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getItemproductos() {
        return itemproductos;
    }

    public void setItemproductos(JMenuItem itemproductos) {
        this.itemproductos = itemproductos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        labelNombres = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        itempersona = new javax.swing.JMenuItem();
        itemusuario = new javax.swing.JMenuItem();
        itemroles = new javax.swing.JMenuItem();
        itemproductos = new javax.swing.JMenuItem();
        itemproveedores = new javax.swing.JMenuItem();
        itemclientes = new javax.swing.JMenuItem();
        itemstock = new javax.swing.JMenuItem();
        itemventas = new javax.swing.JMenuItem();
        itemcotizacion = new javax.swing.JMenuItem();
        iteminformacion = new javax.swing.JMenu();
        itemempresa = new javax.swing.JMenuItem();
        itemotros = new javax.swing.JMenu();
        itemreportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(231, 244, 244));

        labelNombres.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(labelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 478, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(labelNombres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setBackground(new java.awt.Color(162, 205, 205));
        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-crear-nuevo-16(1).png"))); // NOI18N
        jMenu1.setText("Nuevo");
        jMenu1.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N

        itempersona.setBackground(new java.awt.Color(220, 240, 240));
        itempersona.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itempersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-persona-de-sexo-masculino-16.png"))); // NOI18N
        itempersona.setText("Persona");
        jMenu1.add(itempersona);

        itemusuario.setBackground(new java.awt.Color(220, 240, 240));
        itemusuario.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-tipo-de-piel-del-cliente-7-16.png"))); // NOI18N
        itemusuario.setText("Usuario");
        jMenu1.add(itemusuario);

        itemroles.setBackground(new java.awt.Color(220, 240, 240));
        itemroles.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemroles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-tipo-de-máscara-de-cuenta-de-usuario-7-16.png"))); // NOI18N
        itemroles.setText("Roles");
        jMenu1.add(itemroles);

        itemproductos.setBackground(new java.awt.Color(220, 240, 240));
        itemproductos.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caja-de-entrega.png"))); // NOI18N
        itemproductos.setText("Productos");
        itemproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemproductosActionPerformed(evt);
            }
        });
        jMenu1.add(itemproductos);

        itemproveedores.setBackground(new java.awt.Color(220, 240, 240));
        itemproveedores.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        itemproveedores.setText("Proveedores");
        itemproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemproveedoresActionPerformed(evt);
            }
        });
        jMenu1.add(itemproveedores);

        itemclientes.setBackground(new java.awt.Color(220, 240, 240));
        itemclientes.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/objetivo.png"))); // NOI18N
        itemclientes.setText("Clientes");
        itemclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemclientesActionPerformed(evt);
            }
        });
        jMenu1.add(itemclientes);

        itemstock.setBackground(new java.awt.Color(220, 240, 240));
        itemstock.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/almacen.png"))); // NOI18N
        itemstock.setText("Stock");
        itemstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemstockActionPerformed(evt);
            }
        });
        jMenu1.add(itemstock);

        itemventas.setBackground(new java.awt.Color(220, 240, 240));
        itemventas.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venta-al-por-mayor.png"))); // NOI18N
        itemventas.setText("Ventas");
        itemventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemventasActionPerformed(evt);
            }
        });
        jMenu1.add(itemventas);

        itemcotizacion.setBackground(new java.awt.Color(220, 240, 240));
        itemcotizacion.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemcotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cotizacion.png"))); // NOI18N
        itemcotizacion.setText("Cotización");
        itemcotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcotizacionActionPerformed(evt);
            }
        });
        jMenu1.add(itemcotizacion);

        jMenuBar1.add(jMenu1);

        iteminformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informacion.png"))); // NOI18N
        iteminformacion.setText("Informacion");
        iteminformacion.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N

        itemempresa.setBackground(new java.awt.Color(220, 240, 240));
        itemempresa.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemempresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edificio.png"))); // NOI18N
        itemempresa.setText("Empresa");
        iteminformacion.add(itemempresa);

        jMenuBar1.add(iteminformacion);

        itemotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas (1).png"))); // NOI18N
        itemotros.setText("Otros");
        itemotros.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N

        itemreportes.setBackground(new java.awt.Color(220, 240, 240));
        itemreportes.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        itemreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reporte.png"))); // NOI18N
        itemreportes.setText("Reportes");
        itemotros.add(itemreportes);

        jMenuBar1.add(itemotros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemproductosActionPerformed

    private void itemproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemproveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemproveedoresActionPerformed

    private void itemclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemclientesActionPerformed

    private void itemstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemstockActionPerformed

    private void itemventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemventasActionPerformed

    private void itemcotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcotizacionActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemclientes;
    private javax.swing.JMenuItem itemcotizacion;
    private javax.swing.JMenuItem itemempresa;
    private javax.swing.JMenu iteminformacion;
    private javax.swing.JMenu itemotros;
    private javax.swing.JMenuItem itempersona;
    private javax.swing.JMenuItem itemproductos;
    private javax.swing.JMenuItem itemproveedores;
    private javax.swing.JMenuItem itemreportes;
    private javax.swing.JMenuItem itemroles;
    private javax.swing.JMenuItem itemstock;
    private javax.swing.JMenuItem itemusuario;
    private javax.swing.JMenuItem itemventas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelNombres;
    // End of variables declaration//GEN-END:variables
}
