/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Papeleria_Bella.vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author JimmGM
 */
public class Vreportes extends javax.swing.JFrame {

    /**
     * Creates new form Vreportes
     */
    public Vreportes() {
        initComponents();
    }

    public JButton getButtonimprimirpersona() {
        return buttonimprimirpersona;
    }

    public void setButtonimprimirpersona(JButton buttonimprimirpersona) {
        this.buttonimprimirpersona = buttonimprimirpersona;
    }

    public JButton getButtonimprimirusuario() {
        return buttonimprimirusuario;
    }

    public void setButtonimprimirusuario(JButton buttonimprimirusuario) {
        this.buttonimprimirusuario = buttonimprimirusuario;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getLabelcodigo() {
        return labelcodigo;
    }

    public void setLabelcodigo(JLabel labelcodigo) {
        this.labelcodigo = labelcodigo;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        buttonimprimirpersona = new javax.swing.JButton();
        buttonimprimirusuario = new javax.swing.JButton();

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel17.setText("Código:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        jLabel2.setText("Reportes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel18.setText("Imprimir Persona con dos Parámetros:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel22.setText("Imprimir Usuario con dos Parámetros:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));
        getContentPane().add(labelcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 130, 30));

        buttonimprimirpersona.setBackground(new java.awt.Color(232, 255, 255));
        buttonimprimirpersona.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        buttonimprimirpersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer (5)_1.png"))); // NOI18N
        buttonimprimirpersona.setText("Imprimir");
        getContentPane().add(buttonimprimirpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, 40));

        buttonimprimirusuario.setBackground(new java.awt.Color(232, 255, 255));
        buttonimprimirusuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        buttonimprimirusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer (5)_1.png"))); // NOI18N
        buttonimprimirusuario.setText("Imprimir");
        getContentPane().add(buttonimprimirusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonimprimirpersona;
    private javax.swing.JButton buttonimprimirusuario;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel labelcodigo;
    // End of variables declaration//GEN-END:variables
}
