/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package V93Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VistaEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form VistaEmpresa
     */
    public VistaEmpresa() {
        initComponents();
        
        
        
        
    }

    public JButton getBtnBuscarEmpresa() {
        return btnBuscarEmpresa;
    }

    public void setBtnBuscarEmpresa(JButton btnBuscarEmpresa) {
        this.btnBuscarEmpresa = btnBuscarEmpresa;
    }

    public JTextField getTxtbuscarEmpresa() {
        return txtbuscarEmpresa;
    }

    public void setTxtbuscarEmpresa(JTextField txtbuscarEmpresa) {
        this.txtbuscarEmpresa = txtbuscarEmpresa;
    }

    public JLabel getLabelFotoEmpresa() {
        return LabelFotoEmpresa;
    }

    public void setLabelFotoEmpresa(JLabel LabelFotoEmpresa) {
        this.LabelFotoEmpresa = LabelFotoEmpresa;
    }

    public JTable getTableEmpresa() {
        return TableEmpresa;
    }

    public void setTableEmpresa(JTable TableEmpresa) {
        this.TableEmpresa = TableEmpresa;
    }

    public JButton getBtnAgregarFotoEmpresa() {
        return btnAgregarFotoEmpresa;
    }

    public void setBtnAgregarFotoEmpresa(JButton btnAgregarFotoEmpresa) {
        this.btnAgregarFotoEmpresa = btnAgregarFotoEmpresa;
    }

    public JButton getBtnEliminarEmpresa() {
        return btnEliminarEmpresa;
    }

    public void setBtnEliminarEmpresa(JButton btnEliminarEmpresa) {
        this.btnEliminarEmpresa = btnEliminarEmpresa;
    }

    public JButton getBtnGuardarEmpresa() {
        return btnGuardarEmpresa;
    }

    public void setBtnGuardarEmpresa(JButton btnGuardarEmpresa) {
        this.btnGuardarEmpresa = btnGuardarEmpresa;
    }

    public JButton getBtnImprimirEmpresa() {
        return btnImprimirEmpresa;
    }

    public void setBtnImprimirEmpresa(JButton btnImprimirEmpresa) {
        this.btnImprimirEmpresa = btnImprimirEmpresa;
    }

    public JButton getBtnModificarEmpresa() {
        return btnModificarEmpresa;
    }

    public void setBtnModificarEmpresa(JButton btnModificarEmpresa) {
        this.btnModificarEmpresa = btnModificarEmpresa;
    }

    public JButton getBtnNuevoEmpresa() {
        return btnNuevoEmpresa;
    }

    public void setBtnNuevoEmpresa(JButton btnNuevoEmpresa) {
        this.btnNuevoEmpresa = btnNuevoEmpresa;
    }

    public JComboBox<String> getjComboBoxEstadoEmpresa() {
        return jComboBoxEstadoEmpresa;
    }

    public void setjComboBoxEstadoEmpresa(JComboBox<String> jComboBoxEstadoEmpresa) {
        this.jComboBoxEstadoEmpresa = jComboBoxEstadoEmpresa;
    }

    public JTextField getTxtActividadEmpresa() {
        return txtActividadEmpresa;
    }

    public void setTxtActividadEmpresa(JTextField txtActividadEmpresa) {
        this.txtActividadEmpresa = txtActividadEmpresa;
    }

    public JTextField getTxtCelularEmpresa() {
        return txtCelularEmpresa;
    }

    public void setTxtCelularEmpresa(JTextField txtCelularEmpresa) {
        this.txtCelularEmpresa = txtCelularEmpresa;
    }

    public JTextField getTxtCiudadEmpresa() {
        return txtCiudadEmpresa;
    }

    public void setTxtCiudadEmpresa(JTextField txtCiudadEmpresa) {
        this.txtCiudadEmpresa = txtCiudadEmpresa;
    }

    public JTextField getTxtCorreoEmpresa() {
        return txtCorreoEmpresa;
    }

    public void setTxtCorreoEmpresa(JTextField txtCorreoEmpresa) {
        this.txtCorreoEmpresa = txtCorreoEmpresa;
    }

    public JTextField getTxtDireccionEmpresa() {
        return txtDireccionEmpresa;
    }

    public void setTxtDireccionEmpresa(JTextField txtDireccionEmpresa) {
        this.txtDireccionEmpresa = txtDireccionEmpresa;
    }

    public JTextField getTxtNombreEmpresa() {
        return txtNombreEmpresa;
    }

    public void setTxtNombreEmpresa(JTextField txtNombreEmpresa) {
        this.txtNombreEmpresa = txtNombreEmpresa;
    }

    public JTextField getTxtRucEmpresa() {
        return txtRucEmpresa;
    }

    public void setTxtRucEmpresa(JTextField txtRucEmpresa) {
        this.txtRucEmpresa = txtRucEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelFotoEmpresa = new javax.swing.JLabel();
        txtRucEmpresa = new javax.swing.JTextField();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtActividadEmpresa = new javax.swing.JTextField();
        txtDireccionEmpresa = new javax.swing.JTextField();
        txtCiudadEmpresa = new javax.swing.JTextField();
        txtCelularEmpresa = new javax.swing.JTextField();
        txtCorreoEmpresa = new javax.swing.JTextField();
        jComboBoxEstadoEmpresa = new javax.swing.JComboBox<>();
        btnAgregarFotoEmpresa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEmpresa = new javax.swing.JTable();
        btnGuardarEmpresa = new javax.swing.JButton();
        btnModificarEmpresa = new javax.swing.JButton();
        btnEliminarEmpresa = new javax.swing.JButton();
        btnNuevoEmpresa = new javax.swing.JButton();
        btnImprimirEmpresa = new javax.swing.JButton();
        txtbuscarEmpresa = new javax.swing.JTextField();
        btnBuscarEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATOS DE LA EMPRESA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("RUC:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ACTIVIDAD:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DIRECCION:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CIUDAD:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CELULAR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("CORREO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ESTADO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        LabelFotoEmpresa.setText("FOTO");
        getContentPane().add(LabelFotoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 34, 260, 230));
        getContentPane().add(txtRucEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 220, -1));
        getContentPane().add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 220, -1));
        getContentPane().add(txtActividadEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 220, -1));
        getContentPane().add(txtDireccionEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 220, -1));
        getContentPane().add(txtCiudadEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 220, -1));
        getContentPane().add(txtCelularEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 220, -1));
        getContentPane().add(txtCorreoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 220, -1));

        jComboBoxEstadoEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        getContentPane().add(jComboBoxEstadoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 220, -1));

        btnAgregarFotoEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarFotoEmpresa.setText("AGREGAR FOTO");
        getContentPane().add(btnAgregarFotoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        TableEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "NOMBRE", "ACTIVIDAD", "DIRECCION", "CIUDAD", "CELULAR", "CORREO", "ESTADO", "FOTO"
            }
        ));
        jScrollPane1.setViewportView(TableEmpresa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 730, 210));

        btnGuardarEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/GuardarTodo.png"))); // NOI18N
        btnGuardarEmpresa.setText("GUARDAR");
        getContentPane().add(btnGuardarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        btnModificarEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Actualizar (2).png"))); // NOI18N
        btnModificarEmpresa.setText("MODIFICAR");
        getContentPane().add(btnModificarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        btnEliminarEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar.png"))); // NOI18N
        btnEliminarEmpresa.setText("ELIMINAR");
        getContentPane().add(btnEliminarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        btnNuevoEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nuevo.png"))); // NOI18N
        btnNuevoEmpresa.setText("NUEVO");
        getContentPane().add(btnNuevoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        btnImprimirEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimirEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/print.png"))); // NOI18N
        btnImprimirEmpresa.setText("IMPRIMIR");
        getContentPane().add(btnImprimirEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, -1, -1));
        getContentPane().add(txtbuscarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 220, -1));

        btnBuscarEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarEmpresa.setText("BUSCAR EMPRESA");
        getContentPane().add(btnBuscarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFotoEmpresa;
    private javax.swing.JTable TableEmpresa;
    private javax.swing.JButton btnAgregarFotoEmpresa;
    private javax.swing.JButton btnBuscarEmpresa;
    private javax.swing.JButton btnEliminarEmpresa;
    private javax.swing.JButton btnGuardarEmpresa;
    private javax.swing.JButton btnImprimirEmpresa;
    private javax.swing.JButton btnModificarEmpresa;
    private javax.swing.JButton btnNuevoEmpresa;
    private javax.swing.JComboBox<String> jComboBoxEstadoEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtActividadEmpresa;
    private javax.swing.JTextField txtCelularEmpresa;
    private javax.swing.JTextField txtCiudadEmpresa;
    private javax.swing.JTextField txtCorreoEmpresa;
    private javax.swing.JTextField txtDireccionEmpresa;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtRucEmpresa;
    private javax.swing.JTextField txtbuscarEmpresa;
    // End of variables declaration//GEN-END:variables
}
