/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package V93Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VistaRol extends javax.swing.JFrame {

    /**
     * Creates new form VistaRol
     */
    public VistaRol() {
        initComponents();
        
    }

    public JButton getBtnbuscarr() {
        return btnbuscarr;
    }

    public void setBtnbuscarr(JButton btnbuscarr) {
        this.btnbuscarr = btnbuscarr;
    }

    public JTextField getTxtbuscarr() {
        return txtbuscarr;
    }

    public void setTxtbuscarr(JTextField txtbuscarr) {
        this.txtbuscarr = txtbuscarr;
    }

    public JComboBox<String> getjComboBoxRol() {
        return jComboBoxRol;
    }

    public void setjComboBoxRol(JComboBox<String> jComboBoxRol) {
        this.jComboBoxRol = jComboBoxRol;
    }

    public JTable getTableRol() {
        return TableRol;
    }

    public void setTableRol(JTable TableRol) {
        this.TableRol = TableRol;
    }

    public JButton getBtnEliminarRol() {
        return btnEliminarRol;
    }

    public void setBtnEliminarRol(JButton btnEliminarRol) {
        this.btnEliminarRol = btnEliminarRol;
    }

    public JButton getBtnGuardarRol() {
        return btnGuardarRol;
    }

    public void setBtnGuardarRol(JButton btnGuardarRol) {
        this.btnGuardarRol = btnGuardarRol;
    }

    public JButton getBtnModificarRol() {
        return btnModificarRol;
    }

    public void setBtnModificarRol(JButton btnModificarRol) {
        this.btnModificarRol = btnModificarRol;
    }

    public JButton getBtnNuevoRol() {
        return btnNuevoRol;
    }

    public void setBtnNuevoRol(JButton btnNuevoRol) {
        this.btnNuevoRol = btnNuevoRol;
    }

    public JTextField getTxtCodigoRol() {
        return txtCodigoRol;
    }

    public void setTxtCodigoRol(JTextField txtCodigoRol) {
        this.txtCodigoRol = txtCodigoRol;
    }

    public JTextField getTxtDesceipcionRol() {
        return txtDesceipcionRol;
    }

    public void setTxtDesceipcionRol(JTextField txtDesceipcionRol) {
        this.txtDesceipcionRol = txtDesceipcionRol;
    }

    public JTextField getTxtNombreRol() {
        return txtNombreRol;
    }

    public void setTxtNombreRol(JTextField txtNombreRol) {
        this.txtNombreRol = txtNombreRol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoRol = new javax.swing.JTextField();
        txtNombreRol = new javax.swing.JTextField();
        txtDesceipcionRol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRol = new javax.swing.JTable();
        btnGuardarRol = new javax.swing.JButton();
        btnModificarRol = new javax.swing.JButton();
        btnEliminarRol = new javax.swing.JButton();
        btnNuevoRol = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        btnbuscarr = new javax.swing.JButton();
        txtbuscarr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ROL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CODIGO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DESCRIPCION:");

        TableRol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CARGO", "DESCRIPCION", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(TableRol);

        btnGuardarRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardarRol.setText("GUARDAR");

        btnModificarRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarRol.setText("MODIFICAR");

        btnEliminarRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarRol.setText("ELIMINAR");

        btnNuevoRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoRol.setText("NUEVO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ESTADO:");

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        btnbuscarr.setText("BUSCAR POR CARGO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnGuardarRol)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarRol)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoRol)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoRol)
                                    .addComponent(txtNombreRol)
                                    .addComponent(txtDesceipcionRol)
                                    .addComponent(jComboBoxRol, 0, 231, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnbuscarr, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtbuscarr, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDesceipcionRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarRol)
                    .addComponent(btnModificarRol)
                    .addComponent(btnEliminarRol)
                    .addComponent(btnNuevoRol))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaRol().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableRol;
    private javax.swing.JButton btnEliminarRol;
    private javax.swing.JButton btnGuardarRol;
    private javax.swing.JButton btnModificarRol;
    private javax.swing.JButton btnNuevoRol;
    private javax.swing.JButton btnbuscarr;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigoRol;
    private javax.swing.JTextField txtDesceipcionRol;
    private javax.swing.JTextField txtNombreRol;
    private javax.swing.JTextField txtbuscarr;
    // End of variables declaration//GEN-END:variables
}
