/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package V93Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VistaFactura extends javax.swing.JFrame {

    /**
     * Creates new form VistaFactura
     */
    public VistaFactura() {
        initComponents();
        
        
    }

    public JLabel getLabelTotalaPagar() {
        return LabelTotalaPagar;
    }

    public void setLabelTotalaPagar(JLabel LabelTotalaPagar) {
        this.LabelTotalaPagar = LabelTotalaPagar;
    }

    public JTable getTableFactura() {
        return TableFactura;
    }

    public void setTableFactura(JTable TableFactura) {
        this.TableFactura = TableFactura;
    }

    public JButton getBtnEliminarFactura() {
        return btnEliminarFactura;
    }

    public void setBtnEliminarFactura(JButton btnEliminarFactura) {
        this.btnEliminarFactura = btnEliminarFactura;
    }

    public JButton getBtnGenerarFactura() {
        return btnGenerarFactura;
    }

    public void setBtnGenerarFactura(JButton btnGenerarFactura) {
        this.btnGenerarFactura = btnGenerarFactura;
    }

    public JTextField getTxtCantidadFactura() {
        return txtCantidadFactura;
    }

    public void setTxtCantidadFactura(JTextField txtCantidadFactura) {
        this.txtCantidadFactura = txtCantidadFactura;
    }

    public JTextField getTxtCedulaClienteFactura() {
        return txtCedulaClienteFactura;
    }

    public void setTxtCedulaClienteFactura(JTextField txtCedulaClienteFactura) {
        this.txtCedulaClienteFactura = txtCedulaClienteFactura;
    }

    public JTextField getTxtCodigoProFactura() {
        return txtCodigoProFactura;
    }

    public void setTxtCodigoProFactura(JTextField txtCodigoProFactura) {
        this.txtCodigoProFactura = txtCodigoProFactura;
    }

    public JTextField getTxtDescripcionProFactura() {
        return txtDescripcionProFactura;
    }

    public void setTxtDescripcionProFactura(JTextField txtDescripcionProFactura) {
        this.txtDescripcionProFactura = txtDescripcionProFactura;
    }

    public JTextField getTxtNombreClienteFactura() {
        return txtNombreClienteFactura;
    }

    public void setTxtNombreClienteFactura(JTextField txtNombreClienteFactura) {
        this.txtNombreClienteFactura = txtNombreClienteFactura;
    }

    public JTextField getTxtPrecioFactura() {
        return txtPrecioFactura;
    }

    public void setTxtPrecioFactura(JTextField txtPrecioFactura) {
        this.txtPrecioFactura = txtPrecioFactura;
    }

    public JTextField getTxtStockFactura() {
        return txtStockFactura;
    }

    public void setTxtStockFactura(JTextField txtStockFactura) {
        this.txtStockFactura = txtStockFactura;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarFactura = new javax.swing.JButton();
        txtCodigoProFactura = new javax.swing.JTextField();
        txtDescripcionProFactura = new javax.swing.JTextField();
        txtCantidadFactura = new javax.swing.JTextField();
        txtPrecioFactura = new javax.swing.JTextField();
        txtStockFactura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFactura = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGenerarFactura = new javax.swing.JButton();
        txtCedulaClienteFactura = new javax.swing.JTextField();
        txtNombreClienteFactura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LabelTotalaPagar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("DESCRIPCION:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 84, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 84, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("PRECIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 84, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("STOCK DISPONIBLE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 84, -1, -1));

        btnEliminarFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar.png"))); // NOI18N
        btnEliminarFactura.setText("ELIMINAR");
        getContentPane().add(btnEliminarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 77, -1, -1));
        getContentPane().add(txtCodigoProFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 90, -1));

        txtDescripcionProFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionProFacturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtDescripcionProFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 112, 136, -1));

        txtCantidadFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadFacturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadFacturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidadFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 112, 88, -1));

        txtPrecioFactura.setEditable(false);
        txtPrecioFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioFacturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecioFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 112, 85, -1));

        txtStockFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockFacturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtStockFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 112, 122, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Nventa.png"))); // NOI18N
        jLabel6.setText("FACTURA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 11, -1, -1));

        TableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TableFactura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 826, 206));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CEDULA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 379, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("NOMBRE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 379, -1, -1));

        btnGenerarFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/print.png"))); // NOI18N
        btnGenerarFactura.setText("G.FACTURA");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 362, -1, -1));
        getContentPane().add(txtCedulaClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 417, 131, -1));
        getContentPane().add(txtNombreClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 417, 161, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/money.png"))); // NOI18N
        jLabel9.setText("TOTAL A PAGAR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 387, -1, -1));

        LabelTotalaPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelTotalaPagar.setText("---------------------");
        getContentPane().add(LabelTotalaPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 455, 114, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionProFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionProFacturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionProFacturaKeyTyped

    private void txtCantidadFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadFacturaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadFacturaKeyPressed

    private void txtCantidadFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadFacturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadFacturaKeyTyped

    private void txtPrecioFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioFacturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFacturaKeyTyped

    private void txtStockFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockFacturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockFacturaKeyTyped

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTotalaPagar;
    private javax.swing.JTable TableFactura;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadFactura;
    private javax.swing.JTextField txtCedulaClienteFactura;
    private javax.swing.JTextField txtCodigoProFactura;
    private javax.swing.JTextField txtDescripcionProFactura;
    private javax.swing.JTextField txtNombreClienteFactura;
    private javax.swing.JTextField txtPrecioFactura;
    private javax.swing.JTextField txtStockFactura;
    // End of variables declaration//GEN-END:variables
}
